# Generated by Django 5.2.6 on 2025-09-22 11:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='transactions.category', verbose_name='Родительская категория')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма бюджета')),
                ('period', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('yearly', 'Ежегодный')], default='monthly', max_length=10, verbose_name='Период')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'ordering': ['-start_date', 'category'],
                'unique_together': {('user', 'category', 'period', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'), models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_cb8cb9_idx')],
            },
        ),
    ]
